[discord]
token = "xxxxxx-your-discord-bot-token"
message_style = "multiline" # options are: "multiline", "oneline", "text"

[messagestyles]
	[messagestyles.rich]
	chat_message_ready_room_color = [75, 78, 82]
	chat_message_marine_color = [50, 127, 180]
	chat_message_alien_color = [246, 92, 0]
	chat_message_spectator_color = [211, 215, 207]
	player_join_color = [67, 181, 129]
	player_leave_color = [237, 72, 102]
	status_color = [250, 166, 26]

	[messagestyles.text]
	chat_message_format = "%s __[%t]__ **%p**: %m" # %p - player, %m - message, %t - teamspecific prefix, %s - serverspecific prefix
	chat_message_ready_room_prefix = "RR"
	chat_message_marine_prefix = "M"
	chat_message_alien_prefix = "A"
	chat_message_spectator_prefix = "S"
	player_join_format = "%s %p joined %m"
	player_leave_format = "%s %p left %m"

[steam]
web_api_key = "xxxxxx-your-steam-web-api-key" # leave empty to deactivate steam avatars

[servers]
    [servers.example1]
    channelID = "123456789012345678"
    statusChannelID = ""
    admins = ["YourDiscordUser#1234", "123456789012345678"]
    keyword_notifications = [ ["@admin", "@op"], ["My Admin Role", "YourDiscordUser#1234", "123456789012345678"], ]
    muted = ["MutedUser#5678"]
    server_chat_message_prefix = ""
    server_status_message_prefix = "<:apheriox:298852163759898624> "
    server_icon_url = "https://cdn.discordapp.com/icons/123456789012345678/example_icon_hash.png" # leave empty for guild icon
    webadmin = "http://127.0.0.1:8080"
    log_file_path                = "/path/to/Natural Selection 2/log-Server.txt"

    [servers.example2]
    channelID = "123456789012345679"
    webadmin = "http://127.0.0.1:8081"
    log_file_path                = "/path/to/Natural Selection 2/log-Server-2.txt"
